name: Auto Update Worker

on:
  #push:
  #  branches:
  #    - main
  schedule:
    - cron: "0 20 * * 3" # 每天周三凌晨4点运行
  workflow_dispatch:
    inputs:
      force_update:
        description: '是否强制更新（忽略版本检查）'
        required: false
        default: 'false'

permissions:
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.checkver.conclusion }}
      update: ${{ steps.checkver.outputs.update }}
      VERSION: ${{ steps.checkver.outputs.VER }}
    steps:
      - name: 检出仓库
        uses: actions/checkout@v4

      - name: 检查并更新 Worker
        id: checkver
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 使用 GitHub Token 认证
        run: |
          # 日志函数
          log() { echo "[$(date +'%Y-%m-%d %H:%M:%S')] $1"; }

          log "开始检查更新..."

          # 获取本地版本
          LOCAL_VERSION=$(cat version.txt 2>/dev/null || echo "")
          log "本地版本: ${LOCAL_VERSION:-无}"

          # 获取最新 Release
          log "获取最新 Release 信息..."
          REPO_URL=https://api.github.com/repos/bia-pain-bache/BPB-Worker-Panel/releases
          RESPONSE=$(curl -s --retry 3 -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" "$REPO_URL")
          if [ $? -ne 0 ]; then
            log "ERROR: 无法访问 GitHub API"
            exit 1
          fi

          TAG_NAME=$(echo "$RESPONSE" | jq -r '.[0].tag_name')
          log "最新版本: $TAG_NAME" 
          echo "VER=${TAG_NAME}" >> "$GITHUB_OUTPUT"  

          # 判断是否需要更新
          FORCE_UPDATE=${{ github.event.inputs.force_update || 'false' }}
          if [ "$LOCAL_VERSION" = "$TAG_NAME" ] && [ "$FORCE_UPDATE" != "true" ]; then
            log "已是最新版本，无需更新"
            echo "update=false" >> "$GITHUB_OUTPUT"
          else
            echo "update=true" >> "$GITHUB_OUTPUT"
          fi      
  update:
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.update == 'true'
    steps:
      - name: clone code
        env:
          VERSION: ${{needs.check.outputs.VER}}
        run: |
          # 克隆分支代码
          git clone --single-branch --branch $VERSION https://github.com/bia-pain-bache/BPB-Worker-Panel.git
          cd BPB-Worker-Panel
          git checkout $VERSION
          
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Install dependencies
        run: |
          cd BPB-Worker-Panel
          npm install

      - name: Build project
        run: |
          cd BPB-Worker-Panel
          npm run build

      - name: clean code
        env:
          VERSION: ${{needs.check.outputs.VER}}
        run: |
          cd BPB-Worker-Panel
          cp  dist/worker.js  ../_worker.js
          cd ..
          rm -r BPB-Worker-Panel
          echo "$VERSION" > version.txt
          log() { echo "更新完成，新版本: $VERSION"; }

      - name: 提交更改
        if: success() # 仅在更新成功时提交
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🔄 自动同步 Worker 版本: ${{ needs.check.outputs.VER || '未知' }}"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
